name: deployment
on: [ workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: install gradle
        uses: gradle/actions/setup-gradle@v3
      - name: test code
        run: ./gradlew test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      jar-name: ${{steps.publish.outputs.jar-name}}
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: install gradle
        uses: gradle/actions/setup-gradle@v3
      - name: build app
        run: ./gradlew build
      - name: publish jar name
        id: publish
        run: find build/libs/*plain.jar -type f -execdir echo 'jar-name={}'  >> $GITHUB_OUTPUT ';'
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-jar
          path: build/libs/*.jar
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-jar
      - name: output content
        run: ls
      - name: output jar name
        run: echo "${{needs.build.outputs.jar-name}}"
      - name: deploy
        run: echo "deploying  ..."