name: issue-workflow
on: workflow_dispatch
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - name: output event
        run: echo "${{toJSON(github.event)}}"
      - name: print secret
        run: echo "${{toJSON(secrets)}}"
      - name: print secret token
        run: echo "${{secrets.GITHUB_TOKEN}}"